spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pad?serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: register.com.entity

logging:
  config: classpath:log4j2.xml
  level:
    cn.jay.repository: info